const images = [
    { id: 1, src: './assets/images/panorama-1.jpg', alt: 'Panorama-1' },
    { id: 2, src: './assets/images/panorama-2.jpg', alt: 'Panorama-2' },
    { id: 3, src: './assets/images/panorama-3.jpg', alt: 'Panorama-3' },
    { id: 4, src: './assets/images/panorama-4.jpg', alt: 'Panorama-4' },
    { id: 5, src: './assets/images/panorama-5.jpg', alt: 'Panorama-5' },
    { id: 6, src: './assets/images/panorama-6.jpg', alt: 'Panorama-6' },
    { id: 7, src: './assets/images/panorama-7.jpg', alt: 'Panorama-7' },
    { id: 8, src: './assets/images/panorama-8.jpg', alt: 'Panorama-8' },
    { id: 9, src: './assets/images/panorama-9.jpg', alt: 'Panorama-9' },
    { id: 10, src: './assets/images/panorama-10.jpg', alt: 'Panorama-10' },
    { id: 11, src: './assets/images/panorama-11.jpg', alt: 'Panorama-11' },
    { id: 12, src: './assets/images/panorama-12.jpg', alt: 'Panorama-12' },
    { id: 13, src: './assets/images/panorama-13.jpg', alt: 'Panorama-13' },
    { id: 14, src: './assets/images/panorama-14.jpg', alt: 'Panorama-14' },
    { id: 15, src: './assets/images/panorama-15.jpg', alt: 'Panorama-15' },
    { id: 16, src: './assets/images/panorama-16.jpg', alt: 'Panorama-16' },
    { id: 17, src: './assets/images/panorama-17.jpg', alt: 'Panorama-17' },
    { id: 18, src: './assets/images/panorama-18.jpg', alt: 'Panorama-18' },
    { id: 19, src: './assets/images/panorama-19.jpg', alt: 'Panorama-19' },
    { id: 20, src: './assets/images/panorama-20.jpg', alt: 'Panorama-20' },
    { id: 21, src: './assets/images/panorama-21.jpg', alt: 'Panorama-21' },
    { id: 22, src: './assets/images/panorama-22.jpg', alt: 'Panorama-22' },
    { id: 23, src: './assets/images/panorama-23.jpg', alt: 'Panorama-23' },
    { id: 24, src: './assets/images/panorama-24.jpg', alt: 'Panorama-24' },
    { id: 25, src: './assets/images/panorama-25.jpg', alt: 'Panorama-25' },
    { id: 26, src: './assets/images/panorama-26.jpg', alt: 'Panorama-26' },
    { id: 27, src: './assets/images/panorama-27.jpg', alt: 'Panorama-27' },
    { id: 28, src: './assets/images/panorama-28.jpg', alt: 'Panorama-28' },
    { id: 29, src: './assets/images/panorama-29.jpg', alt: 'Panorama-29' },
    { id: 30, src: './assets/images/panorama-30.jpg', alt: 'Panorama-30' },
    { id: 31, src: './assets/images/panorama-31.jpg', alt: 'Panorama-31' },
    { id: 32, src: './assets/images/panorama-32.jpg', alt: 'Panorama-32' },
    { id: 33, src: './assets/images/panorama-33.jpg', alt: 'Panorama-33' },
    { id: 34, src: './assets/images/panorama-34.jpg', alt: 'Panorama-34' },
    { id: 35, src: './assets/images/panorama-35.jpg', alt: 'Panorama-35' },
    { id: 36, src: './assets/images/panorama-36.jpg', alt: 'Panorama-36' },
]

export default images